Emmanuelle-S/Mingle

backend/src/models/UserManager.js
Création des fichiers
userController.js
userManager.js
Modification des fichiers
router.js
index.js dans le dossier models
=> creation des controler/manager de la table user

backend/src/auth.js, backend/src/controllers/userControllers.js, package-lock.json, package.json
Ajout de la méthode .hash d'argon2 pour hacher le mdp lors de la création d'un nouvel utilisateur
Adding Argon2 Hash Method to Hash Password During User Creation
Importation de la librairie Argon2
Importing the Argon2 Library
const argon2 = require("argon2")
Dans la méthode add ajout de la méthode .hash : 
In the Add Method, Add the .hash Method
user.user_pass = await argon2.hash(user.user_pass);
=> hashage de mpd

backend/index.js, backend/src/controllers/categoryserviceControllers.js, backend/src/controllers/serviceControllers.js, backend/src/models/CategoryServiceManager.js, backend/src/models/ServiceManager.js, backend/src/models/index.js, backend/src/router.js
=> feat: implémentation des routes, des manager et des controllers update

backend/.env.sample
ajout de variable dans l'exemple de env
=> feat: mise a jour de .env.sample

frontend/index.html, frontend/src/App.jsx, frontend/src/components/Carousel/Carousel.jsx, frontend/src/pages/Home.css, frontend/src/pages/Home.jsx, frontend/tailwind.config.js, package-lock.json, package.json
Début du dev de la page Home. Modification de fichiers : frontend/index.html; frontend/src/App.jsx; frontend/src/pages/Home.jsx; frontend/tailwind.config.js; package-lock.json; package.json; frontend/src/components/Carousel/; frontend/src/pages/Home.css; frontend/src/components/Card/. ATTENTION bien regarder le fichier : frontend/tailwind.config.js. + Intégration du dossier Card avec ses fichiers
=> PR : Fin de l'intégration du background-color sur Index et du carousel dans Carousel.jsx

frontend/src/components/Card/Card.jsx, frontend/src/components/Carousel/Carousel.jsx, frontend/src/pages/Home/Home.jsx, frontend/src/pages/Message/Message.jsx
Feature : ajout du composant article et préparation de ses props
=> Ajout du composant article

frontend/src/App.jsx, frontend/src/components/Formulaire/Formulaire.jsx, frontend/src/components/Header/Header.jsx
=> fix: apparition du header

frontend/src/components/NotFound/NotFound.jsx, frontend/src/components/NotFound/NotFound.module.css
création de classe générique pour moudle css
=> style: integration de module css et classe générique

frontend/src/components/ConnexionInscritpion/Connexion.jsx, frontend/src/components/ConnexionInscritpion/Inscription.jsx, frontend/src/pages/ConnexionInscription/ConnexionInscription.jsx, frontend/tailwind.config.js
added features for the mobile version :
=> added features for the mobile version

frontend/src/App.jsx, frontend/src/components/Profil/PersonalInfo.jsx, frontend/src/components/Profil/RecentChats.jsx, frontend/src/components/Profil/ServicesCarousel.jsx, frontend/src/pages/Profil/Profil.jsx
1 parent /Page/Profil/Profil.jsx
3 enfants /components/Profil
Reste : 
* Tout à relier au backend / Everything linked to the backend
* Faire les tests userloggin ou non / Run userloggin tests or not
* Améliorer le css / Improve CSS
* ......
=> Start of profile component (public and private) + css

frontend/src/components/Formulaire/Formulaire.jsx, frontend/src/components/Header/Header.jsx
Fix: modification du champs de saisie du type string au lieux type passeword
=> fix: mettre le champs de saisie du type string ou lieu de password

frontend/src/components/Carousel/Carousel.jsx, frontend/src/pages/FAQ/Accordion.jsx, frontend/src/pages/FAQ/FAQ.jsx, frontend/src/pages/Home/Home.jsx, frontend/src/pages/Message/Message.jsx
fix de l'emplacement de l'accroche sur la page Home; maj carousel; intégration des vrais questions/réponses dans la partie faq; et MAJ du style de la partie message
=> Fix: Carrousel / Home / FAQ / Message /

frontend/src/components/Profil/EditProfil.jsx, frontend/src/components/Profil/PersonalInfo.jsx
=> data import from Profil.jsx to EditProfil.jsx completed, PUT missing

frontend/src/App.jsx, frontend/src/components/Profil/EditProfil.jsx, frontend/src/pages/Profil/Profil.jsx, package-lock.json
=> profile and editProfile linked to a logged-in user

backend/src/controllers/conversationControllers.js, backend/src/models/conversationManager.js, backend/src/models/index.js, backend/src/router.js, frontend/src/components/ConnexionInscritpion/Connexion.jsx
Backend intégration conversationManager conversationController +  modif: Connexion.jsx (ajout commentaire) index.js dans backend/src/models et du router
=> feat: conversationManager conversationControllers

frontend/src/components/Profil/EditProfil.jsx, frontend/src/pages/Profil/Profil.jsx
=> add comment

frontend/src/App.jsx, frontend/src/pages/Message/Message.jsx
=> feat: Chat: enfin fonctionnelle

frontend/src/components/ConnexionInscritpion/Inscription.jsx, frontend/src/components/Listedeservice/CardList.jsx
fix; supression sous categorie et description sur les 9 cards
=> fix: supression description  et sous categorie de service

backend/src/controllers/serviceControllers.js, backend/src/models/ServiceManager.js, backend/src/router.js, frontend/src/App.jsx, frontend/src/components/AnimatedRoutes/AnimatedRoutes.jsx, frontend/src/components/DetailsDeService/CardDetails.jsx, frontend/src/components/DetailsDeService/DetailsService.jsx
Voici les premières affichage des Details de service:
=> les premiere affichage des Details de service

frontend/src/App.jsx, frontend/src/components/AnimatedRoutes/AnimatedRoutes.jsx, frontend/src/components/Footer/Footer.jsx
Création du footer responsive
Creating a responsive footer
Les liens Conditions d'utilisation et Politique de confidentialité ne fonctionnent pas je ne sais pas encore pourquoi je vais me pencher dessus.
Conditions d'utilisation and Politique de confidentialité  links don't work, I'm not sure why I'm going to look into them.
Le app.jsx semble pas mal modifié mais c'est juste que j'ai formaté le code correctement. Les conflits avec les modifications de Guillaume sont normalement réglés
La seule réelle modification est l'import du footer
The app.jsx looks modified but it's just that I formatted the code correctly. Conflicts with Guillaume's modifications are normally resolved.
The only real modification is the footer import
Link are ok
=> create footer responsive,  miss some link

frontend/src/components/Header/Header.jsx
Header avant : 
Header maintenant : 
Lorsqu'on est pas connecté et qu'on clique sur publier un service => redirige vers Connexion
Lorsqu'on est connecté et qu'on clique sur publier un service => redirige vers le bon composant 
Reste quelques soucis à régler
=> modification of header and call to action

frontend/src/components/Header/Header.jsx, package-lock.json, package.json
=> delete About from header

frontend/src/pages/Message/Bubble.jsx
fix: Réglage du css de la bubble (passage en z-60)
=> fix: Réglage du css de la bubble (passage en z-60)

frontend/src/components/ConvertDate/ConvertDate.jsx, frontend/src/components/SearchComponant/SearchComponant.jsx, frontend/src/pages/Home/Home.css, frontend/src/pages/Home/Home.jsx, frontend/src/pages/Message/Message.jsx
Fix: Ajustement du responsive mobile. 
Composant Message en version mobile avait une dimension non prévue. 
Page Home avait besoins de petits ajustements en mobile mais également en desktop.
=> fix: CSS responsive sur la partie Message et la page Home

backend/.env.sample, backend/database/tablepeuplage.sql
feat: sql stat + serveur front example env
=> feat: sql stat + serveur front example env

frontend/src/components/Header/Header.jsx
Correction de la navbar en mobile / mobile navbar edition
Correction des liens de la navbar / navbar links edition
Refacto propre du code
=> fix : link on mobile header correction

frontend/index.html, frontend/src/components/Header/Header.jsx
+ commentaires sur le header.jsx et refacto
=> ajout d'une meta description dans le index.html pour le SEO

frontend/src/components/Carousel/Carousel.jsx, frontend/src/pages/Home/Home.css, frontend/src/pages/Home/Home.jsx
bug css sur le carousel, ajout d'un substitut aux cartes de services pour le contenue du Carousel
=> fix:  css Carousel

backend/src/router.js, backend/src/validators.js
ajout de validator pour les routes post et put de conversation et friend
=> feat:  ConvAndFriendValidators

frontend/src/pages/CardDetail/CardDetails.jsx, frontend/src/pages/Dashboardservice/Dashboardservice.jsx
=> fix: url import env
